name: Distribute Android Artifact

on:
  # Reusable workflows (other workflows can trigger this)
  workflow_call:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Prepare access to everything and decode secrets
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Local properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > ${{ github.workspace }}/local.properties
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /Users/runner/work/keystore.jks
      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > ${{ github.workspace }}/composeApp/google-services.json

      # Prepare the environment
      - name: Build with Gradle and Print Version
        id: gradle
        run: |
          VERSION=$(./gradlew -q printVersionName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout release branch
        run: |
          git fetch origin
          git checkout -b releases/${{ env.VERSION }}
          git pull origin releases/${{ env.VERSION }} --allow-unrelated-histories --no-rebase  # Allow unrelated histories to be merged

      - name: Increase version code
        run: awk '/version-code/ {gsub(/[0-9]+/, ++n)} {print}' n=$(awk -F'"' '/version-code/ {print $2}' gradle/libs.versions.toml) gradle/libs.versions.toml > temp && mv temp gradle/libs.versions.toml

      - name: Create whatsnew file
        run: |
          last_increment_commit=$(git log --grep="Increment version code" -n 1 --pretty=format:"%H")
          mkdir -p ${{ github.workspace }}/whatsnew
          git log --pretty=format:"%s" $last_increment_commit..HEAD | grep -E "/CU-[a-z0-9]+_[^ ]+" | awk -F'_' '{print $2}' | sort | uniq > ${{ github.workspace }}/whatsnew/whatsnew-en-US

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'git@github.com'
          git add gradle/libs.versions.toml
          git add -A
          git commit -m 'Increment version code'
          git push --set-upstream origin releases/${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest changes from remote branch
        run: git fetch origin

      - name: Create Pull Request
        run: |
          gh pr create --title "Release ${{ env.VERSION }}" --body "Automated release of version ${{ env.VERSION }}" --head releases/${{ env.VERSION }} --base master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Android - create a bundle
      - name: Build Android Release
        run: ./gradlew bundleRelease

      # Android - upload the bundle to Google Play Console
      - name: Publish Android to Play Store internal test track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          packageName: augmy.interactive.com
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          releaseFiles: ${{ github.workspace }}/composeApp/build/outputs/bundle/release/composeApp-release.aab
          releaseName: Release version ${{ env.VERSION }}
          whatsNewDirectory: ${{ github.workspace }}/whatsnew
          track: internal
          status: draft
          inAppUpdatePriority: 3