name: Distribute Linux artifact

on:
  # Reusable workflows (other workflows can trigger this)
  workflow_call:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Prepare access to everything
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Local properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > ${{ github.workspace }}/local.properties
          awk '{if ($1 == "storeFile=") print "storeFile=${{ github.workspace }}/keystore.jks"; else print $0}' ${{ github.workspace }}/local.properties > temp && mv temp ${{ github.workspace }}/local.properties
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks
      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > ${{ github.workspace }}/composeApp/google-services.json

      # Prepare the environment
      - name: Build with Gradle and get VERSION (no pipes)
        id: gradle-version
        shell: bash
        run: |
          set -euo pipefail
          VERSION="$(./gradlew -q :composeApp:printVersionName)"   # change :app: if your task lives elsewhere
          VERSION="${VERSION//$'\r'/}"   # remove CR
          VERSION="${VERSION//$'\n'/}"   # remove LF
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Computed VERSION: $VERSION"

      # Linux - Deb
      - name: Build Linux Release
        run: ./gradlew packageReleaseDeb -Pbuildkonfig.flavor=release

      - name: List Files
        run: ls -R ${{ github.workspace }}/composeApp/build/compose/binaries/main-release/deb

      - name: Move and rename DEB file
        run: |
          mkdir -p downloads/${{ env.VERSION }}
          mv ${{ github.workspace }}/composeApp/build/compose/binaries/main-release/deb/augmy_${{ env.VERSION }}-1_amd64.deb ${{ github.workspace }}/Augmy.deb

      - name: Upload DEB file to FTP
        run: |
          curl ftp://${{ secrets.FTP_USERNAME_ENCODED }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_SERVER_DOMAIN }}/www/downloads/${{ env.VERSION }}/ --ftp-create-dirs
          curl -T ${{ github.workspace }}/Augmy.deb ftp://${{ secrets.FTP_SERVER_DOMAIN }}/www/downloads/${{ env.VERSION }}/ --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
          curl -T ${{ github.workspace }}/Augmy.deb ftp://${{ secrets.FTP_SERVER_DOMAIN }}/www/downloads/ --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}